// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/{provider}": {
            "get": {
                "description": "Начать авторизацию по протоколу OAuth 2.0",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth"
                ],
                "summary": "Начать авторизацию по протоколу OAuth 2.0",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название провайдера",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/{provider}/callback": {
            "get": {
                "description": "Завершить авторизацию по протоколу OAuth 2.0",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth"
                ],
                "summary": "Завершить авторизацию по протоколу OAuth 2.0",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название провайдера",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/lab1": {
            "get": {
                "description": "Lab1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab1"
                ],
                "summary": "Lab1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фраза для поиска",
                        "name": "phrase",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата начала периода",
                        "name": "period_from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата окончания периода",
                        "name": "period_to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ruslanonly_university-student-managment-system_src_internal_features_lab1_service.ReportItem"
                            }
                        }
                    }
                }
            }
        },
        "/lab2": {
            "get": {
                "description": "Lab2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab2"
                ],
                "summary": "Lab2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название курса (дисциплины)",
                        "name": "course_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Год",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Семестр",
                        "name": "semester",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ruslanonly_university-student-managment-system_src_internal_features_lab2_service.Lab2ReportItem"
                            }
                        }
                    }
                }
            }
        },
        "/lab3": {
            "get": {
                "description": "Lab3",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab3"
                ],
                "summary": "Lab3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название группы",
                        "name": "group_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ruslanonly_university-student-managment-system_src_internal_features_lab3_service.Lab3ReportItem"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ruslanonly_university-student-managment-system_src_internal_features_lab1_service.ReportItem": {
            "type": "object",
            "properties": {
                "attendance": {
                    "type": "number"
                },
                "periodEnd": {
                    "type": "string"
                },
                "periodStart": {
                    "type": "string"
                },
                "phrase": {
                    "type": "string"
                },
                "studentFullName": {
                    "type": "string"
                }
            }
        },
        "github_com_ruslanonly_university-student-managment-system_src_internal_features_lab2_service.Lab2ReportItem": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "class_name": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                }
            }
        },
        "github_com_ruslanonly_university-student-managment-system_src_internal_features_lab3_service.Lab3ReportItem": {
            "type": "object",
            "properties": {
                "course_name": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "students_attendance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ruslanonly_university-student-managment-system_src_internal_features_lab3_service.Lab3ReportStudent"
                    }
                }
            }
        },
        "github_com_ruslanonly_university-student-managment-system_src_internal_features_lab3_service.Lab3ReportStudent": {
            "type": "object",
            "properties": {
                "planned_quantity": {
                    "type": "integer"
                },
                "student_full_name": {
                    "type": "string"
                },
                "student_grade_book_id": {
                    "type": "integer"
                },
                "visited_quantity": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "University Report Generation System",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
