@startuml

entity Department {

}

entity Group {

}

entity Student {

}

entity Course {

}

entity Schedule {
  date: time
}

entity Class {
  id 
}

entity Material {
  id
  content: text
}

entity Attendance {
  id 
  status: bool
}

entity Specialization {}

Material "*" -- "1" Class

Schedule "1" -- "*" Class
Schedule "1" -- "*" Group

Attendance "*" -- "1" Schedule
Attendance "1" -- "1" Student

Student "*" -- "1" Group

Course "1" -- "*" Class

Course "*" -- "*" Specialization

Department "*" -- "*" Specialization

@enduml