http_server:
  address: ":5001"
  write_timeout: 15
  read_timeout: 15
  idle_timeout: 15
  graceful_shutdown_timeout: 10
  swagger:
    login: "admin"
    password: "admin"
    endpoint: "http://localhost:5001"
cookie:
  secret: "cookie_secret"
  max_age: 3600
logger:
  level: "debug"
providers:
  google:
    client_key: "353483397634-q3k88d41v1idd2q26u25k0amurjgl4p8.apps.googleusercontent.com"
    secret: "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"
    callback_url: "http://localhost:5001/auth/google/callback"
    scopes:
      - "email"
      - "profile"
auth:
  secret: "Hgpt130dgh"
  access_token_ttl: 3600000000000
  redirect_url: "http://localhost:5001/swagger/index.html"
postgres:
  connection_string: "postgres://user:password@localhost:5432/my_database"
elastic:
  connection_string: "http://localhost:9200"
neo:
  uri: "neo4j://localhost:7687"
  user: "neo4j"
  password: "password"
redis:
  host: "localhost:6379"
  user: ""
  password: ""
  db: 0
mongo:
  address: "mongodb://user:password@localhost:27017"